### ISSUE TITLE
p_130086_ error.

### ISSUE THREAD

**Issue by Aceusy** [TheWandererRaven/RavenCoffeeMod#16]
When I installed Raven Brews Core and Raven Coffee mods on my server, it started just fine with no problems. But when I try to join the server with the same mods, I'm getting Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null. The only mods installed on the server and the client are Raven Brews Core and Raven Coffee so it's not caused by another mod. I'm running my server on 1.18.2 Forge, and I tried multiple versions of Forge. I tried 40.1.16 and 40.1.51 both didn't fix the problem.

**Comment by TheWandererRaven** [comment]
This has been fixed, I checked a couple of times and now in a server it seems to work fine with the new mod version. Nonetheless I will keep this open for another week just in case anything else comes up regarding this issue. So, please let me know if you see anything wrong with this new fix
