### ISSUE TITLE
Mod Loading Error

### ISSUE THREAD

**Issue by queso-gato1355** [TheWandererRaven/RavenCoffeeMod#17]
[crash-2022-06-12_14.05.40-fml.txt](https://github.com/TheWandererRaven/RavenCoffeeMod/files/8885263/crash-2022-06-12_14.05.40-fml.txt)

When I installed this Mod and operated Minecraft, there was an error. Raise the Crash Report.

**Comment by TheWandererRaven** [comment]
Thanks for raising this issue, I have to ask vecause it is important, do you have the [Raven Brews Core](https://www.curseforge.com/minecraft/mc-mods/raven-brews-core) installed?
