### ISSUE TITLE
Please enable downloading from 3rd-party launchers!

### ISSUE THREAD

**Issue by LeoDog896** [TheWandererRaven/RavenCoffeeMod#22]
(Reference: https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c)

Many modpacks now depend on your Raven Coffee mod, and adding 3rd party downloading can easily make modpacks that include your mod more accessible in general! I hope you consider this.

**Comment by TheWandererRaven** [comment]
Sure! I don't mind
